Autho/Models/ShipSummaryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Autho.Models
{
    public class ShipSummaryViewModel
    {
        public uint ShipCount { get; set; }
    }
}

Autho/Controllers/ShipSummaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Autho.Models;
using Autho.Services;
using Newtonsoft.Json;

namespace Autho.Controllers
{
    public class ShipSummaryController : Controller
    {
        public IShipProvider ShipProvider { get; set; }
        public ShipSummaryController(IShipProvider shipProvider)
        {
            this.ShipProvider = shipProvider;
        }
        

        // GET: ShipSummary
        public ActionResult Index()
        {
            
            
            return View();
        }

        [HttpPost]
        public JsonResult GetJason(int? length,int? draw)
        {

            var json = new
            {
                draw = draw ?? 0,
                recordsTotal = ShipProvider.GetAllShips().Count(),
                recordsFiltered = 10,
                data = ShipProvider.GetAllShips()
            };

            return Json(json, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ShipStat()
        {
            return View("ShipStats");
        }

    }
}

Autho/Views/ShipSummary/Index.cshtml
@model IEnumerable<Autho.Models.Ship>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<table id="example" class="display" style="width:100%">
    <thead>
        <tr>
            <th>name</th>
            <th>CaptainName</th>
            <th>NumCannons</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th>name</th>
            <th>CaptainName</th>
            <th>NumCannons</th>
        </tr>
    </tfoot>
</table>


<script>
    $(document).ready(function () {

        var dt = {
            "processing": true,
            "serverSide": true,
            "ajax": {
                "url": "@Url.Action("GetJason", "ShipSummary")",
                "type": "POST"
            },
            "columns": [
                { "data": "name" },
                { "data": "CaptainName" },
                { "data": "NumCannons" },

            ],
            "createdRow": function (row, data, dataIndex) {
                $(row).dblclick(function () {
                    console.log(data);
                });
            },
            "rowCallback": function (row, data, index) {
                if ((index + 1) % 2 == 0) {
                    console.log($(row).children("td:first").html("goose"));
                }
            },
            scrollX: true,
            scrollY: true,

        };
        //Javascript does not like this
        //console.log("do the print thing up here");
        //if (madeUp3) {
        //    console.log("in if");
        //    dt.madeUp3 = madeUp3;
        //}
        //console.log("do the print thing");
        //console.log(dt);

        $('#example').DataTable(dt);
    });
</script>

Autho/Views/ShipSummary/ShipStats.cshtml
@{
    ViewBag.Title = "ShipStats";
}

<h2>ShipStats</h2>

@Html.Partial("ShipCard")